package com.hyy.jingweibo.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JWBACCOUNT.
 */
public class JWBAccount {

    private Long id;
    private String name;
    private String profile;
    private String description;
    private String access_token;
    private Long expires_in;

    public JWBAccount() {
    }

    public JWBAccount(Long id) {
        this.id = id;
    }

    public JWBAccount(Long id, String name, String profile, String description, String access_token, Long expires_in) {
        this.id = id;
        this.name = name;
        this.profile = profile;
        this.description = description;
        this.access_token = access_token;
        this.expires_in = expires_in;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProfile() {
        return profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAccess_token() {
        return access_token;
    }

    public void setAccess_token(String access_token) {
        this.access_token = access_token;
    }

    public Long getExpires_in() {
        return expires_in;
    }

    public void setExpires_in(Long expires_in) {
        this.expires_in = expires_in;
    }

}
