package com.hyy.jingweibo.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JWBDOWNLOAD_PICS.
 */
public class JWBDownloadPics {

    private Long id;
    private String url;
    private String path;
    private Long size;
    private Long time;
    private Integer type;

    public JWBDownloadPics() {
    }

    public JWBDownloadPics(Long id) {
        this.id = id;
    }

    public JWBDownloadPics(Long id, String url, String path, Long size, Long time, Integer type) {
        this.id = id;
        this.url = url;
        this.path = path;
        this.size = size;
        this.time = time;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
